---
title: "EV Power - Lab 4 Project Report"
format: typst
---

## **Part 0: libraries**

```{r}
library(tidyverse)
library(readr)
library(stringr)
library(dplyr)
library(ggplot2)
library(sf)
library(maps)
```

## **Part 1:** **Defining Research Question**

Chosen Question: Do states with more EV registrations tend to have cheaper electricity?

## **Part 2: Data Preparation and Cleaning**

```{r}
# fixing messy data from csv: av-energy

# read in the messy CSV (skip extra rows if needed)
energy_cost_raw <- read_csv("data/av-energy-price-2021-2023.csv", skip = 2)
energy_cost_raw

# Split the one column into four depending on where there is a comma
energy_cost_raw <- separate(
    energy_cost_raw,
    col = 1,
    into = c("State", "2021", "2022", "2023"),
    sep = ","
)

# preview data
head(energy_cost_raw)

# clean the table using regex
energy_cost <- energy_cost_raw |>
    mutate(across(
        c(`2021`, `2022`, `2023`),
        ~ as.numeric(str_extract(.x, "\\d+\\.?\\d*"))
    ))
head(energy_cost)
```

```{r}
# fixing messy data from csv: messy-ev-registrations
ev_reg <- read_csv("data/ev-registrations-by-state-2023.csv", skip = 2)
ev_reg

# cleaning ev_reg
names(ev_reg) <- names(ev_reg) |>
    str_trim() |>
    str_to_lower() |>
    str_replace_all("[-_]", " ") |>
    str_replace_all("\\s+", "_") |>
    str_remove_all("\\(.*\\)") # remove units like (2023)

head(ev_reg)

ev_reg <- ev_reg |>
    mutate(count_evs = str_extract(count_evs, "\\d+") %>% as.numeric())
head(ev_reg)
```

```{r, error=TRUE, warning=FALSE}
# choosing the year 2023 because only have one year of data for EV registrations

# state names are not equal, so must first change state names so they can be joined
# adding DC to list of state names
state_fulls <- c(datasets::state.name, "District of Columbia")
state_fulls
state_abbs <- c(datasets::state.abb, "DC")
state_abbs

state_lookup <- tibble(state_fulls, state_abbs) # maybe
state_lookup # maybe

# matching state abbreviations to full names and replacing full names with abbrvs
matching <- match(energy_cost$State, state_abbs)
matching
energy_cost$State <- ifelse(is.na(matching), ev_reg$State, state_fulls[matching])

head(energy_cost)

# subsetting only 2023 year of energy costs
energy_cost_2023 <- energy_cost[,c(1,4)]

# renaming columns
colnames(energy_cost_2023) <- c("state", "cost")
energy_cost_2023
colnames(ev_reg) <- (c("state", "count_of_regs"))

ev_reg
energy_cost_2023
```

## **Part 3: Joining / Pivoting Datasets for Analysis**

```{r}
# Now that the tables have the same state names, join them:

ev_reg_to_energy_cost <- full_join(ev_reg, energy_cost_2023, by = "state")

#remove total column at bottom
ev_reg_to_energy_cost <- ev_reg_to_energy_cost[1:51,]
print(ev_reg_to_energy_cost, n=52)
```

## **Part 4: Mapping Visualization**

```{r}
length(energy_cost_2023$cost)
energy_cost_2023$cost[52]

us_average_cost <- mean(ev_reg_to_energy_cost$cost)
us_average_cost

ev_reg_to_energy_cost <- ev_reg_to_energy_cost |>
    mutate(energy_cost_vs_average = (cost / us_average_cost))
```

```{r}
# mapping ratio of energy cost

# create map of US states
states_map <- st_as_sf(map("state", plot = FALSE, fill = TRUE))

# Match state names: map names are lowercase
ev_reg_to_energy_cost$state <- tolower(ev_reg_to_energy_cost$state)
# Join map data
ratio_map <- states_map |>
    left_join(ev_reg_to_energy_cost, by = c("ID" = "state"))
```

```{r}
# map of energy cost in states
ggplot(ratio_map) +
    geom_sf(aes(fill = energy_cost_vs_average), color = "white") +
    scale_fill_gradient2(
        low = "green", mid = "white", high = "red",
        midpoint = 1
    ) +
    labs(
        title = "Electricity Price by State Compared to Average",
        subtitle = "Red = above US average, Green = below US average"
    ) +
    theme_minimal() +
    theme(
        axis.text = element_blank(),
        axis.ticks = element_blank()
)
```

```{r}
# map of number of EVs
ggplot(ratio_map) +
    geom_sf(aes(fill = count_of_regs), color = "white") +
    scale_fill_gradient(
        low = "blue", high = "red"
    ) +
    labs(
        title = "EV Registrations",
        subtitle = "Red = above US average, Blue = below US average"
    ) +
    theme_minimal() +
    theme(
        axis.text = element_blank(),
        axis.ticks = element_blank()
)
```